esgi_blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

app:
    resource: @AppBundle/Controller/
    type: annotation

# USER BUNDLE
user:
    resource: "@UserBundle/Resources/config/routing.yml"

# SONATA ADMIN BUNDLE
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:   /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix:   /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:   /admin

#REST 
rest : 
    type : rest 
    resource : "routing_rest.yml"
    prefix : /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc