Esgi\BlogBundle\Entity\Post:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
        title:
            expose: true
        comments:
            exclude: true
        category:
            exclude: true